export const general_styles = [
  "Watercolor painting of SCENE, wet-on-wet technique on cold-pressed paper, visible brushstrokes, muted ochre and sienna with gold leaf accents and deep ultramarine, figures in flowing ancient robes, atmospheric perspective, classical religious illustration, luminous and contemplative mood",
  "Byzantine art of SCENE, gold leaf background, iconic frontal poses, flattened perspective, rich jewel tones of crimson and lapis lazuli, intricate mosaic-like details, haloed figures, tessellated patterns, ornate borders, spiritual solemnity, tempera on wood panel aesthetic",
  "Photorealistic image of SCENE, 8K resolution, natural Middle Eastern lighting, sharp focus, cinematic composition, authentic period costumes, lifelike textures, dramatic sky, historical accuracy, National Geographic style",
  "Pencil drawing of SCENE, graphite on textured paper, detailed cross-hatching, full tonal range from deep blacks to paper white, precise linework, Gustave Doré inspired, classical biblical illustration, dramatic shadows",
  "Oil painting of SCENE, impasto technique, rich chiaroscuro lighting, Baroque master style, Caravaggio-inspired dramatic contrast, warm amber undertones, canvas texture visible, museum quality, divine light rays",
  "Renaissance fresco of SCENE, Michelangelo and Raphael inspired, soft sfumato technique, earthy pigments on wet plaster, classical idealized figures, architectural framing, Sistine Chapel aesthetic, divine grandeur",
  "Stained glass window depicting SCENE, lead came outlines, jewel-toned translucent panels, Gothic cathedral style, radiant backlighting, geometric segmentation, medieval religious iconography, sacred luminosity",
  "Illuminated manuscript of SCENE, medieval miniature painting, gold leaf details, intricate borders with vine scrolls, vibrant tempera colors, Book of Kells inspired, vellum texture, Latin decorative lettering",
  "Rembrandt-style painting of SCENE, dramatic tenebrism, warm golden light against deep shadows, intimate emotional portrayal, visible brushwork, Dutch Golden Age aesthetic, profound spiritual depth",
  "Pre-Raphaelite painting of SCENE, hyper-detailed naturalism, jewel-bright colors, flowing robes and hair, lush vegetation, symbolic elements, Rossetti and Hunt inspired, romantic spirituality, soft diffused light",
  "Charcoal sketch of SCENE, expressive gestural strokes, dramatic contrast, smudged edges, raw emotional energy, rough paper texture, chiaroscuro shading, prophetic intensity",
  "Ethiopian Orthodox icon of SCENE, large expressive eyes, frontal poses, bold outlines, vibrant primary colors, geometric patterns, Coptic Christian aesthetic, devotional simplicity, spiritual presence",
];

export const art_styles = [
  // Watercolor variations
  "Watercolor painting of SCENE, wet-on-wet technique on cold-pressed paper, visible brushstrokes, muted ochre and sienna with gold leaf accents and deep ultramarine, figures in flowing ancient robes, atmospheric perspective, classical religious illustration, luminous and contemplative mood",
  "Loose watercolor sketch of SCENE, wet-on-dry technique, bold washes with hard edges, limited palette of burnt umber and indigo, gestural figures, white paper showing through, spontaneous and expressive, plein air aesthetic",
  "Detailed botanical watercolor of SCENE, precise glazing technique on hot-pressed paper, delicate layered washes, muted earth tones with touches of gold, fine detail work, 19th century natural history illustration style, scholarly elegance",
  "Chinese ink wash painting of SCENE, rice paper texture, flowing brushwork, monochromatic ink gradients, negative space emphasis, Zen minimalism, spiritual contemplation, Song Dynasty landscape aesthetic",
  "Watercolor and gouache of SCENE, opaque highlights over transparent washes, vibrant yet earthy palette, textured paper grain visible, golden hour lighting, romantic illustration style, dreamy atmospheric quality",

  // Pencil variations
  "Pencil drawing of SCENE, graphite on textured paper, detailed cross-hatching, full tonal range from deep blacks to paper white, precise linework, Gustave Doré inspired, classical biblical illustration, dramatic shadows",
  "Soft graphite sketch of SCENE, 6B pencil on smooth bristol, subtle gradations, sfumato-like blending, intimate portrait quality, Renaissance study aesthetic, gentle contemplative mood",
  "Technical pencil illustration of SCENE, mechanical precision, stippling and hatching combined, architectural detail, clean linework, academic drawing style, museum quality reproduction",
  "Expressive pencil drawing of SCENE, varied pressure and stroke weight, energetic mark-making, rough sketch quality with refined focal points, Käthe Kollwitz inspired, raw emotional intensity",
  "Silverpoint drawing of SCENE, metallic gray lines on prepared ground, delicate Renaissance technique, fine precise strokes, luminous subtle tones, Leonardo da Vinci study aesthetic, timeless elegance",

  // Charcoal variations
  "Charcoal sketch of SCENE, expressive gestural strokes, dramatic contrast, smudged edges, raw emotional energy, rough paper texture, chiaroscuro shading, prophetic intensity",
  "Vine charcoal drawing of SCENE, soft atmospheric tones, powdery texture, gentle gradations, lifted highlights with eraser, misty ethereal quality, contemplative spirituality",
  "Compressed charcoal portrait of SCENE, rich velvety blacks, bold dramatic marks, toned paper with white chalk highlights, Baroque drama, intense psychological depth",
  "Charcoal and white conte on toned paper of SCENE, three-value study, warm gray mid-tones, sculptural form modeling, classical academy style, dignified monumentality",

  // Conte crayon and sanguine
  "Sanguine chalk drawing of SCENE, warm red-brown earth tones, Renaissance master study style, soft blending, Michelangelo figure studies aesthetic, anatomical grace, cream paper",
  "Conte crayon sketch of SCENE, sepia and white on kraft paper, bold strokes, warm undertones, 19th century academic drawing, Degas inspired, intimate naturalism",
  "Three-color conte drawing of SCENE, sanguine black and white chalk, toned paper, Rubens technique, dynamic figures, Baroque energy, masterful draftsmanship",

  // Ink variations
  "Pen and ink drawing of SCENE, fine nib crosshatching, pure black on white, Albrecht Dürer inspired, meticulous detail, woodcut aesthetic, Northern Renaissance precision",
  "Brush and ink sketch of SCENE, bold calligraphic strokes, wet ink bleeds, spontaneous energy, Rembrandt ink drawing style, expressive economy of line",
  "Sepia ink wash of SCENE, warm brown tones, layered transparent washes, quill pen details, antique manuscript quality, aged paper aesthetic, historical gravitas",

  // Pastel and mixed media
  "Soft pastel drawing of SCENE, velvety texture, blended atmospheric tones, Odilon Redon inspired, dreamlike spiritual quality, muted earth colors with subtle luminosity",
  "Chalk pastel on dark paper of SCENE, dramatic light emerging from shadow, rich pigment texture, Edgar Degas technique, intimate theatrical lighting",
  "Mixed media sketch of SCENE, watercolor wash base with ink line details, pencil shading accents, layered textures, journal illustration style, authentic and personal",
];

export const watercolor_styles = [
  "snowy alpine lake at dawn, peaks mirrored in still water, watercolor on cold-press paper, pale cerulean sky with variegated wash, wet-on-wet mist, ultramarine + payne’s gray shadows, dry-brush grasses in foreground, tranquil, subtle paper texture",
  "lavender fields at sunset with distant farmhouse and cypress, watercolor on cold-press paper, warm alizarin + quinacridone gold glow, soft diffusion at horizon, controlled wet-on-dry rows, romantic calm",
  "rocky coastline and crashing surf, tide pools and gulls, watercolor on cold-press paper, cobalt teal + indigo sea, splatter foam, granulating rock shadows, windswept mood",
  "mist forest of pines, gentle river S-curve, watercolor on cold-press, payne’s gray + sap green palette, layered wet-on-wet fog bands, lost-and-found edges, quiet morning",
  "desert mesa at golden hour, red rock canyon, watercolor on hot-press for crisp edges, burnt sienna + ultramarine neutrals, warm rim-light, dry-brush scrub texture, cinematic",
  "Nordic fjord with calm inlet and steep cliffs, watercolor on cold-press, cool cobalt + neutral tint, atmospheric perspective, variegated sky wash, reflective water",
  "rice terraces at sunrise, mist rolling over hills, watercolor on cold-press, sap green + raw sienna, delicate wet-on-dry terraces, peaceful",
  "Tuscan hills and cypress road, watercolor on cold-press, golden ochre fields, ultramarine shadows, soft sky wash, paper grain visible",
  "torii gate over lake with mountains, watercolor on cold-press, muted crimson accent, pale mist, granulation in distant peaks, tranquil",
  "rainy city park at dusk, wet pavement reflections, watercolor on hot-press, blue-gray palette, wet-on-wet rain haze, crisp trunks wet-on-dry",
  "aurora over snowy pines, watercolor on cold-press, phthalo green + indigo ribbons, soft diffusion, starlight splatter, silent night",
  "Scottish loch with heather hills, watercolor on cold-press, moody ultramarine + quinacridone violet, low clouds, rippled reflections",
  "sunflower valley with rolling hills, watercolor on hot-press, cadmium yellow + sap green, crisp petal accents, airy sky wash",
  "Provence poppies and distant village, watercolor on cold-press, alizarin + sap green, variegated sky, soft horizon bleed, joyful",
  "black sand beach and basalt stacks, watercolor on cold-press, neutral tint + indigo, dramatic surf splatter, misty distance",
  "Amalfi coast vista, watercolor on hot-press, cobalt teal + Naples yellow, sunlit villas, crisp edges in foreground, hazy cliff layers",
  "birch grove in spring rain, watercolor on cold-press, sap green + payne’s gray, soft raindrop blooms, wet bark textures",
  "autumn maple creek, watercolor on cold-press, burnt sienna + quinacridone gold + alizarin, leaf splatter, cool water reflections",
  "glacial lagoon with blue icebergs, watercolor on cold-press, manganese blue + indigo, chilly light, subtle granulation, stillness",
  "Norwegian archipelago, watercolor on cold-press, slate blue + raw umber, atmospheric haze, dotted islets, gentle sea",
  "Patagonian steppe and distant peaks, watercolor on hot-press, raw sienna + ultramarine, dry-brush grass, big sky",
  "tea plantation hills in fog, watercolor on cold-press, sap green + neutral tint, layered terraces, drifting mist",
  "Monument Valley silhouettes, watercolor on hot-press, burnt sienna + purple shadows, blazing sunset wash, high contrast",
  "Irish cliffs and wild sea, watercolor on cold-press, emerald + indigo, white foam splatter, moody overcast",
  "Yosemite valley haze, watercolor on cold-press, cobalt blue + neutral tint, atmospheric layers, soft valley light",
  "Zion canyon narrows, watercolor on hot-press, sienna walls + cool shadows, crisp wet-on-dry edges, reflective stream",
  "Dolomites ridge at dawn, watercolor on cold-press, ultramarine + raw umber neutrals, misty passes, luminous sky wash",
  "Icelandic waterfall and mossy cliffs, watercolor on cold-press, phthalo green + indigo, spray splatter, soft mist veil",
  "English lake district fells, watercolor on cold-press, olive green + payne’s gray, layered rain clouds, glimmering lake",
  "Swiss alpine meadow wildflowers, watercolor on cold-press, sap green + cadmium yellow + quinacridone pink, airy sky",
  "Arctic ice field under pink twilight, watercolor on cold-press, cobalt + magenta, soft horizon glow, crystalline granulation",
  "New England lighthouse at storm’s edge, watercolor on hot-press, indigo sea, white spray splatter, crimson roof accent",
  "mangrove lagoon at golden hour, watercolor on cold-press, teal + olive, glassy reflections, warm rim-light",
  "rice paddies with distant volcano, watercolor on cold-press, sap green + raw sienna, layered fog, quiet sunrise",
  "moody moorland with winding path, watercolor on cold-press, olive + neutral tint, low clouds, sparse heather texture",
  "chalk downs and rolling hills, watercolor on cold-press, sage + sky blue, breezy clouds, distant sheep dots",
  "aurora over fjord village, watercolor on cold-press, phthalo green lights, soft star splatter, icy stillness",
  "tropical cove and palm silhouettes, watercolor on hot-press, turquoise + Naples yellow, sunset wash, calm water",
  "foggy redwood trail, watercolor on cold-press, sap green + neutral tint, towering trunks, soft fog layers",
  "heather moor in violet dusk, watercolor on cold-press, quinacridone violet + payne’s gray, low sun beam",
  "glow over rice terraces after rain, watercolor on cold-press, sap green + warm gold, soft cloud reflections",
  "snowfall over quiet village, watercolor on cold-press, indigo + neutral tint, soft flake splatter, warm windows",
  "Tuscan vineyard at harvest, watercolor on hot-press, olive + burgundy accents, crisp grape rows, golden haze",
  "lake with reed beds at sunrise, watercolor on cold-press, raw sienna + ultramarine, mirror calm, dry-brush reeds",
  "Norway spruce forest in blue hour, watercolor on cold-press, ultramarine + indigo, soft snow glow",
  "Provence lavender coast, watercolor on cold-press, lavender + cobalt teal, sea breeze, horizon haze",
  "Swiss valley with river bend, watercolor on cold-press, cobalt + sap green, atmospheric depth, sun patches",
  "coastal cliffs at sunrise, watercolor on cold-press, warm pink + teal sea, soft surf splatter, gulls",
  "pine lake with morning fog, watercolor on cold-press, neutral tint + sap green, vanishing edges, glass water",
  "red rock arch at sunset, watercolor on hot-press, sienna + purple shadows, crisp silhouette, glowing sky",
  "fjell plateau with tarns, watercolor on cold-press, slate blue + moss green, big sky wash, distant peaks",
  "river delta from above, watercolor on hot-press, teal channels in ochre sands, soft diffusion, aerial calm",
  "Japanese maple by pond, watercolor on cold-press, alizarin + sap green, soft reflections, pebble texture",
  "misty bamboo grove, watercolor on cold-press, sap green + neutral tint, layered stalks, breathy atmosphere",
  "cornfield under storm light, watercolor on cold-press, olive + payne’s gray clouds, silver rain shaft",
  "canyon river S-curve, watercolor on hot-press, sienna walls + cool water, crisp banks, hazy distance",
  "Nordic village with rorbuer huts, watercolor on cold-press, crimson accents, blue-gray sea, low cloud deck",
  "oat meadow with wildflowers, watercolor on cold-press, raw sienna + pink accents, breezy strokes, clear sky",
  "patina harbor at dawn, watercolor on cold-press, teal + rust neutrals, soft mist, gentle reflections",
  "glade with brook and moss stones, watercolor on cold-press, sap green + cobalt, dappled light, soft water edges",
  "aurora over frozen lake, watercolor on cold-press, green ribbons, soft starlight splatter, hushed night",
  "Provence village rooftops, watercolor on hot-press, terracotta + ultramarine shadows, crisp eaves, airy horizon",
  "white cliffs and pebbled shore, watercolor on cold-press, indigo sea, wet stones shine, gulls in distance",
  "apple orchard in bloom, watercolor on cold-press, pink blossom splatter, soft spring sky, gentle breeze",
  "monochrome mist valley, watercolor on cold-press, payne’s gray only, graded washes, deep atmosphere",
  "evening marsh with reeds, watercolor on cold-press, olive + indigo, mirror water, dragonfly dots",
  "vineyard terrace above sea, watercolor on cold-press, olive + teal, sun sparks on water, hazy headlands",
  "desert dunes at blue hour, watercolor on hot-press, ultramarine + sienna complements, smooth gradients",
  "mountain pass road, watercolor on cold-press, neutral tint + sap green, fog bands, headlights glow",
  "citrus grove hillside, watercolor on cold-press, cadmium yellow + sap green, dappled shadows, sunlit zest",
  "lake with autumn birches, watercolor on cold-press, gold + crimson leaves, soft ripples, cool sky",
  "coastal dune grasses, watercolor on cold-press, raw sienna + teal sea, dry-brush grass texture, airy clouds",
  "misty hemlock forest, watercolor on cold-press, olive + neutral tint, soft fog stairs, quiet trail",
  "lagoon sandbar and clear shallows, watercolor on hot-press, turquoise + beige, soft edge transitions, serene",
  "dolomite meadow at noon, watercolor on cold-press, sap green + cobalt, puffy clouds, soft ridge line",
  "savanna acacia at sunset, watercolor on hot-press, orange glow + payne’s gray silhouettes, long shadows",
  "bayou cypress knees, watercolor on cold-press, olive + indigo water, fog drift, heron accent",
  "chalk cliffs and grassy headland, watercolor on cold-press, sage + teal, hazy horizon, soft surf",
  "snowy canal with footbridge, watercolor on cold-press, payne’s gray + warm window lights, gentle snow",
  "forest lake mirror with lily pads, watercolor on cold-press, sap green + cobalt, still reflections, soft light",
  "highland valley with stream, watercolor on cold-press, olive + neutral tint, wind-torn clouds, rugged calm",
  "granite coast tide pools, watercolor on cold-press, teal + slate, crisp wet-on-dry rocks, soft sky",
  "storm clearing over prairie, watercolor on cold-press, olive + payne’s gray clouds, long sunbeams",
];

export const biblical_events = [
  "The Creation of Stars: God, Celestial Light, The Firmament",
  "The Naming of Animals: Adam, Wisdom and Connection, Eden",
  "The Breath of Life: God and Adam, The Human Spirit, Eden",
  "Enoch Walking with God: Enoch, Fellowship, The Pre-Flood World",
  "Abel’s Heartfelt Offering: Abel, Sincerity, The Altar of Sacrifice",
  "Noah Building the Ark: Noah, Obedience and Labor, Shinar",
  "The Dove Returning with Olive Leaf: The Dove, Peace and Hope, The Ark",
  "The Hospitality of Sarah: Sarah, Generosity, The Tent at Mamre",
  "Isaac and Rebekah’s First Meeting: Isaac and Rebekah, Romantic Love, The Negev Desert",
  "Jacob Wrestling the Angel: Jacob, Spiritual Perseverance, Peniel",
  "Rachel at the Well: Jacob and Rachel, Love at First Sight, Haran",
  "Joseph’s Coat of Many Colors: Jacob and Joseph, Fatherly Favor, Hebron",
  "Joseph Resisting Temptation: Joseph and Potiphar’s Wife, Integrity, Egypt",
  "Joseph Weeping over his Brothers: Joseph, Emotional Release, Pharaoh’s Palace",
  "Moses and the Burning Bush: Moses, Holy Awe, Mount Horeb",
  "The Pillar of Cloud and Fire: The Israelites, Divine Guidance, The Wilderness",
  "The Manna from Heaven: The Israelites, Providence and Gratitude, Desert of Sin",
  "The Crafting of the Tabernacle: Bezalel, Artistic Inspiration, Sinai",
  "The Shining Face of Moses: Moses, Reflected Glory, Mount Sinai",
  "Joshua and the Commander of the Lord’s Army: Joshua, Humility, Jericho",
  "Rahab Hiding the Spies: Rahab, Courageous Faith, Jericho",
  "The Song of Deborah: Deborah and Barak, Victory and Spirit, Mount Tabor",
  "Gideon’s Fleece: Gideon, Seeking Truth, The Threshing Floor",
  "Samson’s Final Sacrifice: Samson, Redemptive Strength, The Temple of Dagon",
  "Hannah’s Silent Prayer: Hannah, Deep Devotion, The Tabernacle at Shiloh",
  "Samuel Anointing David: Samuel and David, Hidden Greatness, Bethlehem",
  "David’s Dance before the Ark: David, Uninhibited Joy, Jerusalem",
  "Abigail Interceding for Peace: Abigail, Diplomacy and Grace, The Wilderness of Maon",
  "Solomon’s Dream of Wisdom: Solomon and God, Intellectual Virtue, Gibeon",
  "Elijah and the Chariot of Fire: Elijah and Elisha, Spiritual Power, The Jordan River",
  "Elisha Multiplying the Widow’s Oil: Elisha and the Widow, Compassion, Israel",
  "Naaman Healing in the Jordan: Naaman, Humility and Restoration, The Jordan River",
  "The Restoration of the Wall: Nehemiah, Community Spirit, Jerusalem",
  "Esther Approaching the King: Esther, Self-Sacrifice, Susa",
  "Job’s Restoration: Job and his Friends, Patience Rewarded, The Land of Uz",
  "The Shepherd’s Psalm: The Shepherd and Sheep, Peace and Security, Green Pastures",
  "The Virtuous Woman: The Proverbs 31 Woman, Industry and Honor, The Household",
  "Isaiah’s Vision of Seraphim: Isaiah, Purity and Calling, The Heavenly Temple",
  "Jeremiah’s Potter and Clay: The Potter, Sovereignty and Shaping, The Potter’s House",
  "Shadrach, Meshach, and Abednego in the Furnace: The Three Youths, Faithfulness, Babylon",
  "Daniel in the Lions' Den: Daniel, Serenity under Pressure, Babylon",
  "Gabriel Visiting Mary: The Angel Gabriel, Divine Favor, Nazareth",
  "The Magnificat: Mary, Soulful Exultation, The Hill Country of Judea",
  "The Shepherds Watching Their Flocks: The Shepherds and Angels, Wonder, Bethlehem",
  "Simeon Holding the Infant Christ: Simeon, Fulfilled Promise, The Temple",
  "The Boy Jesus in the Temple: Jesus and the Teachers, Intellectual Passion, Jerusalem",
  "The Calling of the Fishermen: Jesus and the Disciples, Purpose, Sea of Galilee",
  "The Healing of the Leper: Jesus and the Leper, Touch and Mercy, Galilee",
  "The Centurion’s Faith: The Centurion, Authority and Belief, Capernaum",
  "The Raising of the Widow’s Son: Jesus and the Widow, Compassion, Nain",
  "The Woman with the Alabaster Jar: The Sinful Woman, Tears of Gratitude, Simon’s House",
  "Calming the Storm: Jesus, Peace Amidst Chaos, Sea of Galilee",
  "The Feeding of the Five Thousand: The Multitude, Generosity, Bethsaida",
  "Walking on Water: Jesus and Peter, Courage and Trust, Sea of Galilee",
  "The Healing of the Man Born Blind: Jesus and the Blind Man, Enlightenment, Pool of Siloam",
  "The Good Shepherd Finding the Lost Sheep: The Shepherd, Relentless Love, The Wilderness",
  "Lazarus Coming Forth: Jesus and Lazarus, Life over Death, Bethany",
  "The Triumphal Entry: The Crowds, Collective Joy, The Gates of Jerusalem",
  "Jesus Washing the Disciples' Feet: Jesus, Servanthood, The Upper Room",
  "The Agony in the Garden: Jesus, Internal Conflict and Surrender, Gethsemane",
  "The Penitent Thief on the Cross: Jesus and the Thief, Instant Grace, Calvary",
  "The Women at the Cross: The Marys, Steadfast Loyalty, Golgotha",
  "The Appearance to Thomas: Jesus and Thomas, Understanding and Belief, The Upper Room",
  "The Ascension: Jesus, Transcendence, Mount of Olives",
  "The Healing at the Beautiful Gate: Peter and the Lame Man, Shared Vitality, Jerusalem Temple",
  "Stephen’s Vision of Glory: Stephen, Forgiveness in Death, Outside Jerusalem",
  "Philip and the Ethiopian Eunuch: Philip, Insight and Inclusion, The Road to Gaza",
  "The Conversion of Saul: Paul, Blinding Transformation, The Road to Damascus",
  "Tabitha Being Raised: Peter and Tabitha, Community Love, Joppa",
  "Cornelius’s Vision: Cornelius, Openness to Spirit, Caesarea",
  "The Prison Doors Opening for Peter: The Angel and Peter, Liberation, Jerusalem",
  "Paul and Silas Singing in Prison: Paul and Silas, Joy in Adversity, Philippi",
  "The Lydia’s Conversion: Lydia, Open-Heartedness, Philippi",
  "The Healing Shadows: The Sick and Peter’s Shadow, Collective Hope, Jerusalem Streets",
  "The Fruit of the Spirit Visualization: The Believer, Love, Joy, and Peace, The Inner Soul",
  "The Armor of God: The Believer, Spiritual Readiness, The Heavenly Realms",
  "The Great Cloud of Witnesses: The Saints, Encouragement, The Heavenly Stadium",
  "The Golden Censer of Prayers: The Angel, Intercession, The Heavenly Altar",
  "The Silence in Heaven: The Heavenly Host, Reverence, The Throne Room",
  "The River of the Water of Life: The Saved, Eternal Vitality, The New Jerusalem",
  "The Tree of Life Healing the Nations: The Nations, Unity and Health, The New Jerusalem",
  "Cain’s Envy: Cain and Abel, Jealousy and Malice, The Field",
  "The Tower of Babel: The Builders, Hubris and Confusion, Shinar",
  "Esau Selling His Birthright: Esau and Jacob, Impulsiveness vs Value, The Family Tent",
  "The Golden Calf: The Israelites, Idolatry and Recklessness, The Base of Sinai",
  "Achan’s Hidden Greed: Achan, Deception, The Tent at Gilgal",
  "Delilah Betraying Samson: Delilah, Treachery, The Valley of Sorek",
  "Nabal’s Harshness: Nabal and David’s Men, Greed and Cruelty, Carmel",
  "Jezebel’s False Accusation: Jezebel and Naboth, Injustice and Murder, Jezreel",
  "The Rich Man and Lazarus: The Rich Man, Indifference, The Gates of the Mansion",
  "Judas’s Thirty Pieces of Silver: Judas, Betrayal and Regret, The Temple Court",
  "Herod’s Vain Pride: Herod Agrippa, Arrogance, Caesarea",
  "Ananias and Sapphira’s Deceit: Ananias and Sapphira, Hypocrisy, The Early Church",
  "Simon the Sorcerer Trying to Buy Power: Simon Magus, Corruption, Samaria",
  "The Pharisee and the Tax Collector: The Pharisee, Self-Righteousness, The Temple",
  "The Parable of the Unforgiving Servant: The Servant, Hard-heartedness, The King’s Court",
  "The Money Changers in the Temple: The Merchants, Commercialism of Holy Space, Jerusalem",
  "The Worship of the Beast: The Deceived, Spiritual Blindness, The Earth",
  "The Fall of Babylon the Great: The Merchants, Mourning over Materialism, The Seacoast",
  "The Victory over Death: The Lamb, Ultimate Triumph, The Cosmos",
];
